model_list:
  # OpenAI Models
  - model_name: gpt-4
    litellm_params:
      model: openai/gpt-4
      api_key: os.environ/OPENAI_API_KEY
      
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY

  # Anthropic Models
  - model_name: claude-3-sonnet
    litellm_params:
      model: anthropic/claude-3-sonnet-20240229
      api_key: os.environ/ANTHROPIC_API_KEY
      
  - model_name: claude-3-haiku
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      api_key: os.environ/ANTHROPIC_API_KEY

  # Google Models
  - model_name: gemini-pro
    litellm_params:
      model: gemini/gemini-pro
      api_key: os.environ/GOOGLE_API_KEY

  # Local Ollama Models (optional)
  - model_name: llama2
    litellm_params:
      model: ollama/llama2
      api_base: os.environ/OLLAMA_BASE_URL

# General settings
general_settings:
  master_key: null
  database_url: os.environ/DATABASE_URL
  
# Logging
litellm_settings:
  success_callback: ["langfuse"]
  failure_callback: ["langfuse"]
  set_verbose: true
  
# Rate limiting
router_settings:
  routing_strategy: "least-busy"
  model_group_alias:
    "gpt-4": ["gpt-4"]
    "gpt-3.5": ["gpt-3.5-turbo"]
    "claude": ["claude-3-sonnet", "claude-3-haiku"]
    "gemini": ["gemini-pro"] 

auth_strategy: "header_auth"
user_id_header_name: "X-authentik-username"
user_email_header_name: "X-authentik-email"
