# Traefik Dynamic Configuration for Authentik Forward Auth
http:
  middlewares:
    authentik:
      forwardAuth:
        address: "http://authentik-server:9000/outpost.goauthentik.io/auth/traefik"
        trustForwardHeader: true
        authResponseHeaders:
          - X-authentik-username
          - X-authentik-groups
          - X-authentik-email
          - X-authentik-name
          - X-authentik-uid
          - X-authentik-jwt
          - X-authentik-meta-jwks
          - X-authentik-meta-outpost
          - X-authentik-meta-provider
          - X-authentik-meta-app
          - X-authentik-meta-version

    # Allow public access to certain routes
    public-access:
      chain:
        middlewares:
          - rate-limit

    # Rate limiting middleware
    rate-limit:
      rateLimit:
        burst: 100
        average: 50
        period: "1m"

  routers:
    # Public routes (no authentication required)
    frontend-public:
      rule: "Host(`yourdomain.com`) && (Path(`/`) || PathPrefix(`/public`) || PathPrefix(`/api/v1/auth/status`))"
      service: frontend
      middlewares:
        - public-access
      tls:
        certResolver: letsencrypt

    # Protected routes (authentication required)
    frontend-protected:
      rule: "Host(`yourdomain.com`)"
      service: frontend
      middlewares:
        - authentik
      tls:
        certResolver: letsencrypt
      priority: 100

  services:
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:80"
    
    backend:
      loadBalancer:
        servers:
          - url: "http://backend:8000" 